<template>
  <div>
   <div class="container-fluid SignupForm">
      
      <form action="/charge" method="POST">
      
      <div class="form-row Fname">
        <div class="col-md-4 mb-3">
          <label for="validationDefault01">First name</label>
          <input type="text" class="form-control firstname"  value="" required placeholder="firstname" v-model="firstName" />
        </div>
        <div class="col-md-4 mb-3">
          <label >Last name</label>
          <input type="text" class="form-control lastname"  value="" required placeholder="lastname"  v-model="lastName" /> 
        </div>
        
        <div class="col-md-4 mb-3">
          <label >Email Address</label>
          <input type="text" class="form-control email"  value="" required placeholder="Email Address" v-model="email" />
        </div>
        </div>
        <div class="col-md-4 mb-3">
          <label >Password</label>
          <input type="text" class="form-control password" value="" required placeholder="password" v-model="password" />
        </div>
        <div class="">
       
      </div>
      <div class="btn btn-primary" v-on:click="submitUser()">Submit form</div>
      
    </form>
    </div>

    <div ref="paypal"></div>
  </div>
</template>

<script>
import firebase from 'firebase'
// import image from "../assets/lamp.png"
export default {
  name: "payment",

  data: function() {
    return {
        db: firebase.firestore(),
        firstName: '',
        lastName: '',
        email: '',
        password: '',
      loaded: false,
      paidFor: false,
      product: {
        price: 777.77,
        description: "leg lamp from that one movie",
        img: "./assets/lamp.jpg"
      }
    };
  },
  mounted: function() {
    const script = document.createElement("script");
    script.src =
      "https://www.paypal.com/sdk/js?client-id=AY5TR1gQyaeIgNdw8EuBKyTCsFp1uoerXdKbGzngsLXNjjU2qDxLiW_u32eyV_6yfWdrYFoI19o01Lqq";
    script.addEventListener("load", this.setLoaded);
    document.body.appendChild(script);
  },
  methods: {
    setLoaded: function() {
      this.loaded = true;
      window.paypal
        .Buttons({
          createOrder: (data, actions) => {
            return actions.order.create({
              purchase_units: [
                {
                  description: this.product.description,
                  amount: {
                    currency_code: "USD",
                    value: this.product.price
                  }
                }
              ]
            });
          },
          onApprove: async (data, actions) => {
            const order = await actions.order.capture();
            this.paidFor = true;
            console.log(order);
          },
          onError: err => {
            console.log(err);
          }
        })
        .render(this.$refs.paypal);
    },
    submitUser(e) {
              firebase.auth().
              createUserWithEmailAndPassword(this.email, this.password).then(
                // Login has been created
                returnedLogin => {
                  // Get the returned login data
                  console.log('Successfully created user')
                  alert(`created user for ${this.email} and ${this.password}`)
                  const userData = returnedLogin.user;

                  // Create entry in the database from the login info
                  this.db.collection('users').add({
                    id: userData.uid, // This is the ID generated by the Log In
                    email: userData.email, // This is the email generated by the Log In (same as form)
                    name: `${this.firstName} ${this.lastName}`, // name (from form data)
                    password: this.password
                  })
                }
              )
              .catch((error) => {
                alert(`Could not sign up: ${error.message}`);
                
              })
 
       }
  }
};
</script>