<template>

    <div class="container-fluid SignupForm">
      
      <form action="/charge" method="POST">
      
      <div class="form-row Fname">
        <div class="col-md-4 mb-3">
          <label for="validationDefault01">First name</label>
          <input type="text" class="form-control firstname"  value="" required placeholder="firstname" v-model="firstname" />
        </div>
        <div class="col-md-4 mb-3">
          <label >Last name</label>
          <input type="text" class="form-control lastname"  value="" required placeholder="lastname"  v-model="lastname" /> 
        </div>
        
        <div class="col-md-4 mb-3">
          <label >Email Address</label>
          <input type="text" class="form-control email"  value="" required placeholder="Email Address" v-model="email" />
        </div>
        </div>
        <div class="col-md-4 mb-3">
          <label >Password</label>
          <input type="text" class="form-control password" value="" required placeholder="password" v-model="password" />
        </div>
        <div class="">
        <div class="col-md-4 mb-3">
          <label >address</label>
          <input type="text" class="form-control"  required v-model="address"/>
        </div>
        </div>
        <div >
        <div class="col-md-4 mb-3">
          <label >City</label>
          <input type="text" class="form-control"  required v-model="city"/>
        </div>
        <div class="col-md-4 mb-3">
          <label >State</label>
          <input type="text" class="form-control"  required v-model="state"/>
        </div>
        <div class="col-md-1 mb-3">
          <label >Zip</label>
          <input type="text" class="form-control" required v-model="zip"/>
        </div>
        <div class="col-md-3 mb-3">
          <label >Card number</label>
          <input type="text" class="form-control" required v-model="credit"/>
        </div>
        <div class="col-md-3 mb-3">
          <label > ReEnter Card number</label>
          <input type="text" class="form-control" required v-model="credit"/>
        </div>
        <div class="col-md-2 mb-3">
          <label >expiration date</label>
          <input type="text" class="form-control"  required v-model="cvc"/>
        </div>
        <div class="col-md-1 mb-3">
          <label >CVC</label>
          <input type="text" class="form-control" required v-model="expiration"/>
        </div>
        </div>
        <div class="form-group">
        <div class="form-check">
          <input class="form-check-input" type="checkbox" value="" id="invalidCheck2" required /> 
          <label class="form-check-label" for="invalidCheck2">
            Agree to terms and conditions
          </label>
        </div>
      </div>
      <div class="btn btn-primary" v-on:click="submitUser()">Submit form</div>
      
    </form>
  </div>
 
</template>


<script>
 

import  firebase from 'firebase';
  // import Stripe from 'stripe';
 //import { stripeKey, stripeOptions } from './stripeConfig.json'
//  import { Card, createToken } from 'vue-stripe-elements-plus'
export default {
 
        name: 'signupData',
        data() {
            return {
                
                   firstname: '',
                    lastname: '',
                    city: '',
                    state: '',
                    zip: '',
                    credit: '',
                    cvc: '',
                    expiration: '',
                    password: '',
                    email:'',
                    address:'',
                    db: firebase.firestore(),
                };
        },
        methods: {
            submitUser(e) {
              firebase.auth().
              createUserWithEmailAndPassword(this.email, this.password).then(
                // Login has been created
                returnedLogin => {
                  // Get the returned login data
                  console.log('Successfully created user')
                  alert(`created user for ${this.email} and ${this.password}`)
                  const userData = returnedLogin.user;

                  // Create entry in the database from the login info
                  this.db.collection('users').add({
                    id: userData.uid, // This is the ID generated by the Log In
                    email: userData.email, // This is the email generated by the Log In (same as form)
                    name: `${this.firstname} ${this.lastname}`, // name (from form data)
                    password: this.password
                  })
                }
              )
              .catch((error) => {
                alert(`Could not sign up: ${error.message}`);
                
              })
 
       },
      
       
    }
}
    

</script>


    


<style>
.container-fluid{
  margin-right:100%;
}
.Fname{
  padding-top: 6%;
}
form{
  

}

</style>
